### PR TITLE
something weird happened...

### PR DESCRIPTION
**Pull request by floridop**
I had to restore your file that resulted deleted in my repo. Now I don't understand why you have the correct files in your fork and I don't have them in mine... I'll investigate further.

### CODE REVIEW

**Comment by floridop** [comment]
Oh I see now! The files in your master where never moved to the branch for some reason!! Maybe you should try to branch again and push? check if the file I restored from the history is the same you wanted me to correct, in which case, there's nothing you need to do.

**Comment by AntonMoberg** [comment]
The file you restored is the correct one from what I can see. However in [https://github.com/floridop/MNXB01-2017/tree/master/antmoberg/HW3b](url) the folders dataset and result are missing, is this something I need to be concerned about? And if so do you need me to do something else?

**Comment by floridop** [comment]
I think I'll correct it now and tell you if there is any problem. I don't think there will be need of any action from you because I run automatic tests using different folders than the repositories.

**Comment by floridop** [comment]
I confirm there is no need for you to upload anything. You can either accept this pull request or integrate its changes.

**Pull request merged**
